### ISSUE TITLE
CPU Usage not working

### ISSUE THREAD

**Issue by pawanrao** [seniorquico/Orleans.TelemetryConsumers.ElasticContainerService#1]
I've been using this on AWS ECS and its a great package to track resource usage. 
Looks like memory usage is working fine but CPU usage is always showing at 0% despite having a few thousand grains activated. 

Could this be fixed?

**Comment by seniorquico** [comment]
Hey, @pawanrao! (Sorry for the _loooong_ delay to reply. I didn't see any GitHub notifications.)

Thanks for calling out the issue. The value being reported was off by a factor of 100. I've corrected it in the latest bits.
